[project]
name = "tebe_znak_telegram"
version = "0.1.3"
dependencies = [
    "loguru==0.7.3",
    "toml==0.10.2",
    "aiogram",
    "pytz==2025.2",
    "pigar",
    "sqlalchemy",
    "apscheduler",
    "tabulate",
]
show_publisher_params_on_run = false
debug_mode = true


[publisher]
timezone = "Europe/Moscow"
post_hours = [8, 14, 20]
bot_token = "7064737344:AAFk4zcdHiEcipfWNCXNWabf70lFJch9LAQ"
channels_ids = ["-1002392744548"]

# TODO: хранить айди телеграмм каналов в sqlite с подпиской названий.

#TODO: Конструктор сообщений. Берёт список шаблонных сообщений, где спец символы заменяются на указанное имя для соответствующего канала.
#TODO: Должно быть два шаблона: для женщин и для мужчин.