[project]
name = "tebe_znak_telegram"
version = "0.1.3"
dependencies = [
    "pyTelegramBotAPI==4.10.0",
    "pytz==2025.2",
    "pigar",
    "sqlalchemy",
    "python-telegram-bot",
    "apscheduler",
]


[tokens]
bot_token = "7064737344:AAFk4zcdHiEcipfWNCXNWabf70lFJch9LAQ"
channels_ids = ["-1002290461483", "-1002258674996", "-1002454106093"]

# TODO: хранить айди телеграмм каналов в sqlite с подпиской названий.